Models/County.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Leap.Models
{
    public class County
    {
        public int? StateFips { get; set; }
        public string StateName { get; set; }
        public int? CountyFips { get; set; }
        public string CountyName { get; set; }
        public double? PrimaryLatitude { get; set; }
        public double? PrimaryLongitute { get; set; }
    }
}

Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Xml.Linq;
using System.Xml;
using System.Xml.XPath;
using System.IO;
using System.Xml.Xsl;


namespace Leap.Controllers
{
    //[Authorize]
    public class PollController : LogBaseController
    {
        //
        // GET: /Poll/

        int NUM_OF_SAMPLE_RECORDS = 10;
        int NUM_OF_RECORDS_IN_PAGES = 500;

        [AllowAnonymous]
        public ActionResult Index(string tab, int country_id = 1, string view = null)
        {
            if (!User.IsInRole("Admin")) view = null;

            ViewBag.tab = tab;
            ViewBag.view = view;

            LeapDataClassesDataContext context = new LeapDataClassesDataContext();
            List<Leap.Models.State> list = context.list_loc_keys.Where(s => s.country_id == country_id)
                .Select(s => new Leap.Models.State
                {
                    CountryId = s.country_id,
                    StateFips = s.state_fips,
                    StateName = s.state_name,
                    StateAbbrev = s.state_abbrev
                })
                .OrderBy(s => s.StateName).ToList();
            return View(list);
        }

        [AllowAnonymous]
        public ActionResult Download(string tab, int country_id = 1, string view = null)
        {
            if (!User.IsInRole("Admin")) view = null;

            ViewBag.tab = tab;
            ViewBag.view = view;

            LeapDataClassesDataContext context = new LeapDataClassesDataContext();
            List<Leap.Models.State> list = context.list_loc_keys.Where(s => s.country_id == country_id)
                .Select(s => new Leap.Models.State
                {
                    CountryId = s.country_id,
                    StateFips = s.state_fips,
                    StateName = s.state_name,
                    StateAbbrev = s.state_abbrev
                })
                .OrderBy(s => s.StateName).ToList();
            return View(list);
        }

        [AllowAnonymous]
        public JsonResult AllOfficeNamesInJson(string counties, string ranges)
        {
            var predicate_fips = PredicateBuilder.True<ldc_results_election>();
            if (counties != "")
            {
                string[] fips_array = counties.Split(',');
                predicate_fips = PredicateBuilder.False<ldc_results_election>();
                foreach (string fip_str in fips_array)
                {
                    if (fip_str == "") continue;
                    string[] state_county_fips = fip_str.Split(':');
                    if (state_county_fips[1] == "" || state_county_fips[1] == "-1")
                    {
                        predicate_fips = predicate_fips.Or(e => e.state_fips == int.Parse(state_county_fips[0]));
                    }
                    else
                    {
                        predicate_fips = predicate_fips.Or(e => e.state_fips == int.Parse(state_county_fips[0])
                            && e.county_fips == int.Parse(state_county_fips[1]));
                    }
                }
            }

            // build office clauses
            var predicate_time = PredicateBuilder.True<ldc_results_election>();
            if (ranges != "")
            {
                string[] range_array = ranges.Split(',');
                predicate_time = PredicateBuilder.False<ldc_results_election>();
                foreach (string range_str in range_array)
                {
                    if (range_str == "") continue;
                    string[] time_strs = range_str.Split(':');
                    if (time_strs[0] != "" && time_strs[1] != "")
                    {
                        DateTime from_date = DateTime.Parse(time_strs[0]);
                        DateTime to_date = DateTime.Parse(time_strs[1]);
                        predicate_time = predicate_time.Or(e => e.election_date.Value >= from_date
                            && e.election_date.Value <= to_date);
                    }
                    else if (time_strs[0] != "")
                    {
                        DateTime from_date = DateTime.Parse(time_strs[0]);
                        predicate_time = predicate_time.Or(e => e.election_date.Value >= from_date);
                    }
                    else if (time_strs[1] != "")
                    {
                        DateTime to_date = DateTime.Parse(time_strs[1]);
                        predicate_time = predicate_time.Or(e => e.election_date.Value <= to_date);
                    }
                }
            }

            LeapDataClassesDataContext context = new LeapDataClassesDataContext();
            var list = context.ldc_results_elections
                .Where(e => e.archive_flag == 0)
                .Where(predicate_fips)
                .Where(predicate_time)
                .Where(e => e.leap_office_name_id > 0)
                .Select(e => new
                    {
                        e.leap_office_name_id,
                        e.list_leap_office_name.leap_office_name
                    })
                .Distinct()
                .OrderBy(e => e.leap_office_name)
                .ToList();

            List<Leap.Models.OfficeName> office_names = new List<Leap.Models.OfficeName>();
            foreach (var office in list)
            {
                Leap.Models.OfficeName office_name = new Leap.Models.OfficeName();
                office_name.Id = office.leap_office_name_id.Value;
                office_name.Name = office.leap_office_name;
                office_name.Synonyms = context.list_leap_office_name_synonyms
                    .Where(s => s.leap_office_name_id == office.leap_office_name_id)
                    .OrderBy(s => s.office_name_synonym)
                    .Select(s => s.office_name_synonym )
                    .Distinct().ToList();
                office_names.Add(office_name);
            }
            return Json(office_names, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public JsonResult AllDatesInJson(string counties, string offices)
        {
            var predicate_fips = PredicateBuilder.True<ldc_results_election>();
            if (counties != "")
            {
                string[] fips_array = counties.Split(',');
                predicate_fips = PredicateBuilder.False<ldc_results_election>();
                foreach (string fip_str in fips_array)
                {
                    if (fip_str == "") continue;
                    string[] state_county_fips = fip_str.Split(':');
                    if (state_county_fips[1] == "" || state_county_fips[1] == "-1")
                    {
                        predicate_fips = predicate_fips.Or(e => e.state_fips == int.Parse(state_county_fips[0]));
                    }
                    else
                    {
                        predicate_fips = predicate_fips.Or(e => e.state_fips == int.Parse(state_county_fips[0])
                            && e.county_fips == int.Parse(state_county_fips[1]));
                    }
                }
            }

            // build offices clauses
            var predicate_offices = PredicateBuilder.True<ldc_results_election>();
            if (offices != "")
            {
                string[] office_array = offices.Split(',');
                predicate_offices = PredicateBuilder.False<ldc_results_election>();
                foreach (string office_str in office_array)
                {
                    if (office_str == "-1")
                    {
                        predicate_offices = PredicateBuilder.True<ldc_results_election>();
                        break;
                    }
                    if (office_str == "") continue;
                    predicate_offices = predicate_offices.Or(e => e.leap_office_name_id == int.Parse(office_str));
                }
            }

            LeapDataClassesDataContext context = new LeapDataClassesDataContext();
            var query = context.ldc_results_elections
                .Where(e => e.archive_flag == 0)
                .Where(predicate_fips)
                .Where(predicate_offices)
                .Where(e => e.leap_office_name_id > 0)
                .Select(e => new { e.election_date })
                .Distinct()
                .OrderBy(e => e.election_date);

            string sql = context.GetCommand(query).CommandText;

            var list = query.ToList();

            List<string> dates = new List<string>();
            for (int idx = 0; idx < list.Count; idx++)
            {
                dates.Add(list[idx].election_date.Value.ToString("yyyy-MM-dd"));
            }
            return Json(dates, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public JsonResult AllInJson(int country_id = 1)
        {
            LeapDataClassesDataContext context = new LeapDataClassesDataContext();
            List<Leap.Models.State> list = context.list_loc_keys.Where(s => s.country_id == country_id)
                .Select(s => new Leap.Models.State
                {
                    StateFips = s.state_fips,
                    StateName = s.state_name,
                    StateAbbrev = s.state_abbrev
                })
                .OrderBy(s => s.StateName).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult Find(int? s, string fips, string office, string time, Boolean referendums)
        {
            int start = 0;
            if (s != null) start = s.Value;

            ViewBag.start_index = start;
            ViewBag.fips = fips;
            ViewBag.office = office;
            ViewBag.time = time;
            ViewBag.referendums = referendums.ToString();

            return View();
        }

        [AllowAnonymous]

Views/Shared/_County.cshtml
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyDYbadKvPbz35-4NiP46cI7XMqoYUzfz-k&sensor=false"></script>
	<script type="text/javascript" src="~/Scripts/geoxml3.js"></script>
    <script type="text/javascript" src="~/Scripts/county.js"></script>
    <style type="text/css">
	    html { height: 100% }
        body { height: 100%; margin: 0; padding: 0 }
	    #map_canvas { height: 100% }
    </style>

    <div id="map_canvas" style="width:79%; height:100%; float:left"></div>

Views/Shared/_DivDialog.cshtml
    <div id='__div_data_dialog' class='content' style="display:none">
    	<div id='__div_content'></div>
        <br/>
        <div style="text-align:right">
        	<span id='__ok_button' class="link_text">OK</span>&#160;<span id='__cancel_button' class="link_text">Cancel</span>
        </div>
    </div>

    <div id='__div_wait_dialog' class='content' style="display:none">
        <br />Please wait while processing the request...
    </div>

    <div id='__div_ballot_wait_dialog' class='content' style="display:none">
        <br />Please wait while processing the request...
        <br />
        <center><img src="/Images/animated_ballot_box.gif" /></center>
    </div>

    <div id='__div_message_dialog' class='content' style="display:none">
        <div id='__div_content'></div>
        <br />
        <div style="text-align:right"><span id='__close_button' class="link_text">Close</span></div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
        <meta charset="utf-8" />
        <title>Leap - @ViewBag.Title</title>
        <meta name="viewport" content="width=device-width" />
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web:300,400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
        <link rel="stylesheet" href="~/Content/main.css" />
        <!--<link rel="stylesheet" href="~/Content/bootstrap.css" />
        <link rel="stylesheet" href="~/Content/Site.css" />-->
        <script type="text/javascript" src="~/Scripts/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
        <script type="text/javascript" src="~/Scripts/dropdown.js"></script>
        <!--<script type="text/javascript" src="~/Scripts/bootstrap.js"></script>-->
        <script type="text/javascript" src="~/Scripts/dialog_script.js"></script>
        <!--<script type="text/javascript" src="~/Scripts/ajax_request.js"></script>-->
        <script type="text/javascript" src="~/Scripts/support_text.js"></script>
        @RenderSection("scripts", required: false)

    </head>
    <body>
        <div style="width:100%">
            <table style="width:960px;height:130px" class="loc_center">
                <tr>
                    <td style="width:50%;vertical-align:central;" align="left"><a href="~/"><img src="~/Images/Leap-logo.png" /></a></td>
                    <td style="width:50%;vertical-align:central;" align="right">@Html.Partial("_MenuPartial")</td>
                </tr>
            </table>

            <div class="loc_center" style="margin:0;padding:0">
                <img src="~/Images/color-band.png" />
            </div>

            <div id="body" class="container-fluid" style="width:100%;padding:0;margin:0;margin-top:-8px;">
                @RenderSection("featured", required: false)
                @RenderBody()
            </div>
        </div>

        <br />
        <div style="width:100%;height:120px;background-color:#E73830;font-size:14px">
            <table style="width:960px" class="loc_center">
                <tr>
                    <td style="width:25%;color:#ffffff;padding:8px;margin:8px;">
                        <div>
                            <div style="vertical-align:top;float:left;margin-top:0px">STAY IN TOUCH</div>
                            <div style="vertical-align:top;float:left;margin-left:10px">
                                <img src="~/Images/facebook-icon.png" />
                                <img src="~/Images/twitter-icon.png" />
                            </div>
                        </div>
                    </td>
                    <td style="width:40%;color:#ffffff;padding:8px;margin:8px;">
                        <div>
                            <div style="vertical-align:top;float:left;margin-top:14px">SPONSORS</div>
                            <div style="vertical-align:top;float:left;margin-left:10px">
                                <img src="~/Images/k2i.png" />
                                <img src="~/Images/nse.png" />
                                <img src="~/Images/rice.png" />
                                <img src="~/Images/uwm-rec.png" />
                            </div>
                        </div>                         
                    </td>
                    <td style="width:35%;color:#ffffff;padding:8px;margin:8px;">
                        <div>
                            <div style="vertical-align:top;float:left;margin-top:6px">CONTACT US</div>
                            <div style="vertical-align:top;float:left;color:#000000;margin-left:10px">marschal@rice.edu 713.348.2694</div>
                            <div style="vertical-align:top;float:left;color:#000000;margin-left:10px">shahp@uwm.edu 414.229.3979</div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>

Views/Shared/_MenuPartial.cshtml
<table cellspacing="0" cellpadding="0" id="menu_table">
    <tr class="nav nav-pills">
        <td class="menu_text" id="home" align="left">@Html.ActionLink("Home", "Index", "Home")</td>
        <td style="width:110px">&nbsp;</td>
        <td class="menu_text" id="publication" align="left">@Html.ActionLink("Publications", "Index", "Publication")</td>
    </tr>
    <tr class="nav nav-pills">
        <td class="menu_text" id="about" align="left">@Html.ActionLink("About Us", "About", "Home")</td>
        <td style="width:110px">&nbsp;</td>
        <td class="menu_text" id="service" align="left">@Html.ActionLink("Services", "Index", "Service")</td>
    </tr>
    <tr class="nav nav-pills">
        <td class="menu_text" id="product" align="left">@Html.ActionLink("Products", "Index", "Product")</td>
        <td style="width:110px">&nbsp;</td>
        <td class="menu_text" id="membership" align="left">@Html.ActionLink("Membership", "Index", "Member")</td>
    </tr>
    <tr class="nav nav-pills">
        <td class="menu_text" id="data" align="left">@Html.ActionLink("Data", "Index", "Poll")</td>
        <!--<td align="left">
            <li class="dropdown menu_text" id="data">
                <a class="dropdown-toggle menu_text" data-toggle="dropdown" href="#">Data <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="menu_text">@Html.ActionLink("Availability", "Index", "Poll", new {tab="av"}, null)</li>
                    <li class="menu_text">@Html.ActionLink("Extraction Old", "Ext_old", "Poll", new {tab="ex"}, null)</li>
                    <li class="menu_text">@Html.ActionLink("Extraction New", "Index", "Poll", new {tab="ex"}, null)</li>
                </ul>
            </li>
        </td>-->
        <td style="width:110px">&nbsp;</td>
        @Html.Partial("_LoginPartial")
    </tr>
</table>